greetingMessage = "Hello! I'm Duke"
askingFavour = "What can I do for you?"
dotted = "---------------------------------"

todo_symbol = "T"
deadline_symbol = "D"
event_symbol = "E"
mark_symbol = "X"

emptyDescription_msg = "OOPS!!! The description of a todo cannot be empty"
bye_msg = "Bye. Hope to see you again soon!"
falseCommand = "OOPS!!! I'm sorry, but I don't know what that means :("
list_msg = "Here are the tasks in your list:"
delete_msg = "Noted. I've removed this task:"
taskOk_msg = "Got it. I've added this task:"
list_msg = "Here are the tasks in your list:"
marked_msg = "Nice! I've marked this task as done:"
unmark_msg = "OK, I've marked this task as not done yet:"
find_msg = "Here are the matching tasks in your list:"
missing_arg_msg="Missing argument"
deleted_msg = "Noted. I've removed this task:"
space = " "
inputting_sign = "> "
error_msg = "Error"